services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mary-tq/app:dev
    container_name: mary-tq-dev
    ports:
      - "3000:3000"
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - mary-tq-network
    working_dir: /app
  
networks:
  mary-tq-network:
    driver: bridge
